### ISSUE TITLE
Hello readme example not working

### ISSUE THREAD

**Issue by Shorssaud** [guseggert/clustertest#2]
in the readme example of the hello program:
// setup a BasicCluster which has a much richer API than barebones clusters
	cluster, _ := cluster.New(clusterImpl)

// destroy the nodes and cluster after the test
t.Cleanup(func() { cluster.Cleanup(ctx) })

These lines seem to not function, this seems to fix it:

// setup a BasicCluster which has a much richer API than barebones clusters
c, _ := cluster.New(clusterImpl)
// destroy the nodes and cluster after the test
t.Cleanup(func() { c.Cleanup(ctx) })

**Comment by guseggert** [comment]
Thanks, fixed
